# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test nim classification accuracy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install PCRE3
      run: |
        sudo apt-get install -y libpcre3
    - name: Set up Nim
      run: |
        curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
        sh init.sh -y
    - name: Test with nimble test
      #continue-on-error: true
      run: |
        export PATH=$HOME/.nimble/bin:$PATH
        cd nlzmadetect && nimble test -y
